services:
  product-db:
    image: postgres:16
    container_name: product-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ProductDb
    ports:
      - "5444:5432"  # Sol taraf host (local), sağ taraf container içi port
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  product-api:
    build:
      context: ./Services/ProductService
      dockerfile: Product.API/Dockerfile
    container_name: product-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Host=product-db;Port=5432;Database=ProductDb;Username=postgres;Password=postgres
    ports:
      - "7001:8080"
    depends_on:
      - product-db
    networks:
      - ecommerce-net

volumes:
  product_data:

networks:
  ecommerce-net:
    driver: bridge
