apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: order-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=order-db;Port=5432;Database=OrderServiceDb;Username=postgres;Password=postgres"
        - name: RabbitMQ__HostName
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: hostname
        - name: RabbitMQ__Port
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: port
        - name: RabbitMQ__UserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: RabbitMQ__VirtualHost
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: virtualhost
        - name: RabbitMQ__QueueName
          valueFrom:
            configMapKeyRef:
              name: order-config
              key: queue-name
        - name: RabbitMQ__ExchangeName
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: exchange-name
        - name: RabbitMQ__RoutingKey
          valueFrom:
            configMapKeyRef:
              name: order-config
              key: routing-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: ecommerce
spec:
  selector:
    app: order-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP